name: Deploy Cloud Run


on: [push]

jobs:

  testing-action:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: app

    steps:
      # checkout code
      - uses: actions/checkout@v3

      # docker build (inside working directory -> my-angular-app)
      - name: Build docker image
        run: docker build -t my-app-kubernetes01:latest .


      # setup node (typescript)
      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: 16

      #- name: "npm install"
      #  run: npm install

      # auth GCP
      - name: "auth GCP"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_TOKEN }}"

      # setup gcloud cli
      - name: "setup GCP"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      # configure gcr.io
      - name: "configure gcr.io"
        run: gcloud auth configure-docker gcr.io

      # push image GCR
      - name: "push image in registry"
        run: |
          docker tag my-app-kubernetes01:latest gcr.io/prismatic-fact-334421/my-app-kubernetes01:latest
          docker push gcr.io/prismatic-fact-334421/my-app-kubernetes01:latest

      
      

      # pulumi
      #- name: "exec pulumi"
      #  run: |
      #    curl -fsSL https://get.pulumi.com | sh
      #    export PULUMI_ACCESS_TOKEN=${{secrets.PULUMI_TOKEN}}
      #    pulumi login
      #    pulumi up -s dev -y

      
      #- name: "exec pulumi"
      #  uses:  pulumi/actions@v3
      #  with:
      #    command: up
      #    stack-name: dev
      #  env:
      #    PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}